// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package storepg

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (id, user_id, name, broker, account_type, base_currency, starting_balance, account_kind, capabilities)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, user_id, name, broker, account_type, base_currency, starting_balance, created_at, account_kind, capabilities
`

type CreateAccountParams struct {
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
	Name            string  `json:"name"`
	Broker          string  `json:"broker"`
	AccountType     string  `json:"account_type"`
	BaseCurrency    string  `json:"base_currency"`
	StartingBalance float64 `json:"starting_balance"`
	AccountKind     string  `json:"account_kind"`
	Capabilities    string  `json:"capabilities"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createAccount,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Broker,
		arg.AccountType,
		arg.BaseCurrency,
		arg.StartingBalance,
		arg.AccountKind,
		arg.Capabilities,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.AccountKind,
		&i.Capabilities,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE id = $1 AND user_id = $2
`

type DeleteAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccount, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccount = `-- name: GetAccount :one
SELECT id, user_id, name, broker, account_type, base_currency, starting_balance, created_at, account_kind, capabilities FROM accounts WHERE id = $1 AND user_id = $2
`

type GetAccountParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.ID, arg.UserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.AccountKind,
		&i.Capabilities,
	)
	return i, err
}

const getAccountByIDAny = `-- name: GetAccountByIDAny :one
SELECT id, user_id, name, broker, account_type, base_currency, starting_balance, created_at, account_kind, capabilities FROM accounts WHERE id = $1
`

func (q *Queries) GetAccountByIDAny(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountByIDAny, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.AccountKind,
		&i.Capabilities,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, user_id, name, broker, account_type, base_currency, starting_balance, created_at, account_kind, capabilities FROM accounts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListAccounts(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Broker,
			&i.AccountType,
			&i.BaseCurrency,
			&i.StartingBalance,
			&i.CreatedAt,
			&i.AccountKind,
			&i.Capabilities,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $1, broker = $2, account_type = $3, base_currency = $4, starting_balance = $5, account_kind = $6, capabilities = $7
WHERE id = $8 AND user_id = $9
RETURNING id, user_id, name, broker, account_type, base_currency, starting_balance, created_at, account_kind, capabilities
`

type UpdateAccountParams struct {
	Name            string  `json:"name"`
	Broker          string  `json:"broker"`
	AccountType     string  `json:"account_type"`
	BaseCurrency    string  `json:"base_currency"`
	StartingBalance float64 `json:"starting_balance"`
	AccountKind     string  `json:"account_kind"`
	Capabilities    string  `json:"capabilities"`
	ID              string  `json:"id"`
	UserID          string  `json:"user_id"`
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, updateAccount,
		arg.Name,
		arg.Broker,
		arg.AccountType,
		arg.BaseCurrency,
		arg.StartingBalance,
		arg.AccountKind,
		arg.Capabilities,
		arg.ID,
		arg.UserID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Broker,
		&i.AccountType,
		&i.BaseCurrency,
		&i.StartingBalance,
		&i.CreatedAt,
		&i.AccountKind,
		&i.Capabilities,
	)
	return i, err
}
