// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: news.sql

package storepg

import (
	"context"
	"time"
)

const createNews = `-- name: CreateNews :one
INSERT INTO news (
  id, user_id, title, source, url, published_at, original_text, notes, summary, category, tags
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, title, source, url, published_at, original_text, notes, summary, category, tags, created_at, updated_at
`

type CreateNewsParams struct {
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
	Title        string    `json:"title"`
	Source       string    `json:"source"`
	Url          string    `json:"url"`
	PublishedAt  time.Time `json:"published_at"`
	OriginalText string    `json:"original_text"`
	Notes        string    `json:"notes"`
	Summary      string    `json:"summary"`
	Category     string    `json:"category"`
	Tags         string    `json:"tags"`
}

func (q *Queries) CreateNews(ctx context.Context, arg CreateNewsParams) (News, error) {
	row := q.db.QueryRowContext(ctx, createNews,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Source,
		arg.Url,
		arg.PublishedAt,
		arg.OriginalText,
		arg.Notes,
		arg.Summary,
		arg.Category,
		arg.Tags,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.PublishedAt,
		&i.OriginalText,
		&i.Notes,
		&i.Summary,
		&i.Category,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createNewsAsset = `-- name: CreateNewsAsset :one
INSERT INTO news_assets (
  id, news_id, asset_type, symbol, market, exchange, display_name, relation, source
)
SELECT
  $1, $2, $3, $4,
  $5, $6, $7, $8, $9
WHERE EXISTS (
  SELECT 1 FROM news
  WHERE news.id = $2 AND news.user_id = $10
)
RETURNING id, news_id, asset_type, symbol, market, exchange, display_name, relation, source, created_at, updated_at
`

type CreateNewsAssetParams struct {
	ID          string `json:"id"`
	NewsID      string `json:"news_id"`
	AssetType   string `json:"asset_type"`
	Symbol      string `json:"symbol"`
	Market      string `json:"market"`
	Exchange    string `json:"exchange"`
	DisplayName string `json:"display_name"`
	Relation    string `json:"relation"`
	Source      string `json:"source"`
	UserID      string `json:"user_id"`
}

func (q *Queries) CreateNewsAsset(ctx context.Context, arg CreateNewsAssetParams) (NewsAsset, error) {
	row := q.db.QueryRowContext(ctx, createNewsAsset,
		arg.ID,
		arg.NewsID,
		arg.AssetType,
		arg.Symbol,
		arg.Market,
		arg.Exchange,
		arg.DisplayName,
		arg.Relation,
		arg.Source,
		arg.UserID,
	)
	var i NewsAsset
	err := row.Scan(
		&i.ID,
		&i.NewsID,
		&i.AssetType,
		&i.Symbol,
		&i.Market,
		&i.Exchange,
		&i.DisplayName,
		&i.Relation,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNews = `-- name: DeleteNews :execrows
DELETE FROM news WHERE id = $1 AND user_id = $2
`

type DeleteNewsParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNews(ctx context.Context, arg DeleteNewsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNews, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNewsAsset = `-- name: DeleteNewsAsset :execrows
DELETE FROM news_assets
WHERE news_assets.id = $1 AND EXISTS (
  SELECT 1 FROM news WHERE news.id = news_assets.news_id AND news.user_id = $2
)
`

type DeleteNewsAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteNewsAsset(ctx context.Context, arg DeleteNewsAssetParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNewsAsset, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNews = `-- name: GetNews :one
SELECT id, user_id, title, source, url, published_at, original_text, notes, summary, category, tags, created_at, updated_at FROM news WHERE id = $1 AND user_id = $2
`

type GetNewsParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNews(ctx context.Context, arg GetNewsParams) (News, error) {
	row := q.db.QueryRowContext(ctx, getNews, arg.ID, arg.UserID)
	var i News
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.PublishedAt,
		&i.OriginalText,
		&i.Notes,
		&i.Summary,
		&i.Category,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNewsAsset = `-- name: GetNewsAsset :one
SELECT news_assets.id, news_assets.news_id, news_assets.asset_type, news_assets.symbol, news_assets.market, news_assets.exchange, news_assets.display_name, news_assets.relation, news_assets.source, news_assets.created_at, news_assets.updated_at FROM news_assets
JOIN news ON news.id = news_assets.news_id
WHERE news_assets.id = $1 AND news.user_id = $2
`

type GetNewsAssetParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetNewsAsset(ctx context.Context, arg GetNewsAssetParams) (NewsAsset, error) {
	row := q.db.QueryRowContext(ctx, getNewsAsset, arg.ID, arg.UserID)
	var i NewsAsset
	err := row.Scan(
		&i.ID,
		&i.NewsID,
		&i.AssetType,
		&i.Symbol,
		&i.Market,
		&i.Exchange,
		&i.DisplayName,
		&i.Relation,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNews = `-- name: ListNews :many
SELECT id, user_id, title, source, url, published_at, original_text, notes, summary, category, tags, created_at, updated_at FROM news
WHERE user_id = $1
ORDER BY published_at DESC, id DESC
`

func (q *Queries) ListNews(ctx context.Context, userID string) ([]News, error) {
	rows, err := q.db.QueryContext(ctx, listNews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []News
	for rows.Next() {
		var i News
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Source,
			&i.Url,
			&i.PublishedAt,
			&i.OriginalText,
			&i.Notes,
			&i.Summary,
			&i.Category,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNewsAssets = `-- name: ListNewsAssets :many
SELECT news_assets.id, news_assets.news_id, news_assets.asset_type, news_assets.symbol, news_assets.market, news_assets.exchange, news_assets.display_name, news_assets.relation, news_assets.source, news_assets.created_at, news_assets.updated_at FROM news_assets
JOIN news ON news.id = news_assets.news_id
WHERE news_assets.news_id = $1 AND news.user_id = $2
ORDER BY news_assets.id
`

type ListNewsAssetsParams struct {
	NewsID string `json:"news_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) ListNewsAssets(ctx context.Context, arg ListNewsAssetsParams) ([]NewsAsset, error) {
	rows, err := q.db.QueryContext(ctx, listNewsAssets, arg.NewsID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsAsset
	for rows.Next() {
		var i NewsAsset
		if err := rows.Scan(
			&i.ID,
			&i.NewsID,
			&i.AssetType,
			&i.Symbol,
			&i.Market,
			&i.Exchange,
			&i.DisplayName,
			&i.Relation,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNews = `-- name: UpdateNews :one
UPDATE news SET
  title = $1, source = $2, url = $3, published_at = $4, original_text = $5, notes = $6,
  summary = $7, category = $8, tags = $9, updated_at = CURRENT_TIMESTAMP
WHERE id = $10 AND user_id = $11
RETURNING id, user_id, title, source, url, published_at, original_text, notes, summary, category, tags, created_at, updated_at
`

type UpdateNewsParams struct {
	Title        string    `json:"title"`
	Source       string    `json:"source"`
	Url          string    `json:"url"`
	PublishedAt  time.Time `json:"published_at"`
	OriginalText string    `json:"original_text"`
	Notes        string    `json:"notes"`
	Summary      string    `json:"summary"`
	Category     string    `json:"category"`
	Tags         string    `json:"tags"`
	ID           string    `json:"id"`
	UserID       string    `json:"user_id"`
}

func (q *Queries) UpdateNews(ctx context.Context, arg UpdateNewsParams) (News, error) {
	row := q.db.QueryRowContext(ctx, updateNews,
		arg.Title,
		arg.Source,
		arg.Url,
		arg.PublishedAt,
		arg.OriginalText,
		arg.Notes,
		arg.Summary,
		arg.Category,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	var i News
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Source,
		&i.Url,
		&i.PublishedAt,
		&i.OriginalText,
		&i.Notes,
		&i.Summary,
		&i.Category,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNewsAsset = `-- name: UpdateNewsAsset :one
UPDATE news_assets SET
  asset_type = $1, symbol = $2, market = $3, exchange = $4, display_name = $5, relation = $6,
  source = $7, updated_at = CURRENT_TIMESTAMP
WHERE news_assets.id = $8 AND EXISTS (
  SELECT 1 FROM news WHERE news.id = news_assets.news_id AND news.user_id = $9
)
RETURNING id, news_id, asset_type, symbol, market, exchange, display_name, relation, source, created_at, updated_at
`

type UpdateNewsAssetParams struct {
	AssetType   string `json:"asset_type"`
	Symbol      string `json:"symbol"`
	Market      string `json:"market"`
	Exchange    string `json:"exchange"`
	DisplayName string `json:"display_name"`
	Relation    string `json:"relation"`
	Source      string `json:"source"`
	ID          string `json:"id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) UpdateNewsAsset(ctx context.Context, arg UpdateNewsAssetParams) (NewsAsset, error) {
	row := q.db.QueryRowContext(ctx, updateNewsAsset,
		arg.AssetType,
		arg.Symbol,
		arg.Market,
		arg.Exchange,
		arg.DisplayName,
		arg.Relation,
		arg.Source,
		arg.ID,
		arg.UserID,
	)
	var i NewsAsset
	err := row.Scan(
		&i.ID,
		&i.NewsID,
		&i.AssetType,
		&i.Symbol,
		&i.Market,
		&i.Exchange,
		&i.DisplayName,
		&i.Relation,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
